version: '3'
services:
  api-server:
    container_name: csy-catalog
    restart: always
    build: .
    volumes:
          - './database:/data/db'
    ports:
      - '3000:3000'

#    links:
#      - mongodb
#    depends_on:
#      - mongodb
#  mongodb:
#    container_name: csy-catalog-database
#    restart: always
#    image: mongo:latest
#    volumes:
#      - './database:/data/db'
#    ports:
#      - '27017:27017'
