version: '3'
services:
  app:
    container_name: csy-catalog-server
    restart: always
    build: .
    ports:
      - '3000:3000'
#    links:
#      - mongodb
#    depends_on:
#      - mongodb
#  mongodb:
#    container_name: csy-catalog-database
#    restart: always
#    image: mongo:latest
#    volumes:
#      - './database:/data/db'
#    ports:
#      - '27017:27017'
