version: '3'
services:
  app:
    container_name: catalog-server
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
  mongo:
    container_name: catalog-data-base
    image: mongo
    ports:
      - '27017:27017'
