version: "3"
services:
  app:
    container_name: csy-catalog-server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: csy-catalog-database
    restart: always
    image: mongo
    volumes:
      - ./database:/csy-catalog-database
    ports:
      - '27017:27017'
